import { TEMPLATES } from '../data/templates';
import { AGENT_MAP } from '../data/agents';
import { callGemini } from './gemini';

function delay(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/** Run an async operation but always wait at least `ms` milliseconds, even on error. */
async function withMinDelay(promise, ms) {
  const start = Date.now();
  let result, error;
  try {
    result = await promise;
  } catch (err) {
    error = err;
  }
  const elapsed = Date.now() - start;
  const remaining = ms - elapsed;
  if (remaining > 0) await delay(remaining);
  if (error) throw error;
  return result;
}

function detectTemplate(input) {
  const lower = input.toLowerCase();
  if (lower.includes('nda') || lower.includes('non-disclosure') || lower.includes('confidential')) return 'nda';
  if (lower.includes('real estate') || lower.includes('purchase') || lower.includes('property')) return 'realestate';
  if (lower.includes('sla') || lower.includes('service level') || lower.includes('service agreement')) return 'sla';
  return 'nda';
}

function agentSystemPrompt(agentId) {
  const agent = AGENT_MAP[agentId];
  if (!agent) return 'You are a legal document drafting assistant.';
  return `You are the "${agent.name}" agent.

Role: ${agent.info.role}
Personality: ${agent.info.personality}
Instructions: ${agent.info.instructions}
Expected output: ${agent.info.output}

Rules:
- Write professional, legally-sound document text.
- Use [PLACEHOLDER_NAME] in ALL-CAPS with underscores for values the user must fill in (e.g. [PARTY_A_NAME], [DATE], [AMOUNT]).
- Do NOT use markdown headings or bullet points — write flowing paragraph/clause text only.
- Keep output concise (2-4 short paragraphs max per section).`;
}

/**
 * Run document generation using Gemini for each section.
 */
export async function runGeneration(input, callbacks) {
  const templateKey = detectTemplate(input);
  const template = TEMPLATES[templateKey];

  const doc = {
    title: template.title,
    sections: template.sections.map((s) => ({
      ...s,
      status: 'pending',
      content: null,
    })),
  };

  callbacks.onDocumentInit(doc);

  callbacks.onChatMessage({
    role: 'assistant',
    content: `Generating your ${template.title}. The Chief of Staff is coordinating agents to draft each section using AI.`,
  });

  // Track generated content for context in later sections
  const generatedSections = [];

  // Phase 1: Generate each section with Gemini
  for (let i = 0; i < doc.sections.length; i++) {
    const section = template.sections[i];

    callbacks.onActiveAgent(section.agent, section.agentTask);
    await delay(400);
    callbacks.onSectionStart(i);

    const contextSoFar = generatedSections
      .map((gs) => `- ${gs.title}: ${gs.content.slice(0, 150)}...`)
      .join('\n');

    const userPrompt = `Document type: ${template.title}
Section to write: "${section.title}"
Your task: ${section.agentTask}
User's request: "${input}"

${contextSoFar ? `Previously generated sections for context:\n${contextSoFar}\n\n` : ''}Write the content for this section now. Output only the section text, no heading.`;

    let content;
    try {
      content = await withMinDelay(callGemini(agentSystemPrompt(section.agent), userPrompt), 1500);
    } catch (err) {
      console.error(`Gemini error for section ${section.title}:`, err);
      callbacks.onError?.(`Gemini call failed for "${section.title}" — using fallback`);
      content = section.content;
    }

    generatedSections.push({ title: section.title, content });

    callbacks.onSectionDone(i, content);
    callbacks.onAgentComplete(section.agent);
    await delay(300);
  }

  callbacks.onActiveAgent(null, null);
  await delay(300);

  // Phase 2: Quality Review
  callbacks.onActiveAgent('quality', 'Reviewing full document for consistency, contradictions, and completeness');
  await delay(600);
  callbacks.onQualityReviewStart();

  const fullDoc = generatedSections.map((gs) => `### ${gs.title}\n${gs.content}`).join('\n\n');

  try {
    const reviewResult = await withMinDelay(callGemini(
      agentSystemPrompt('quality'),
      `Review this complete ${template.title} for internal contradictions, undefined terms, ambiguous language, missing cross-references, and overall coherence. If everything looks good, say "All sections verified." Otherwise list the issues briefly.\n\n${fullDoc}`
    ), 2000);
    console.log('Quality review:', reviewResult);
  } catch (err) {
    console.error('Quality review failed:', err);
    callbacks.onError?.('Quality review failed — skipping verification');
  }

  callbacks.onQualityReviewDone();
  callbacks.onAgentComplete('quality');

  callbacks.onChatMessage({
    role: 'assistant',
    content: `Your ${template.title} is ready! All sections were generated by AI and verified by the Quality Review agent. Fill in the [PLACEHOLDER] fields to complete the document.`,
  });

  callbacks.onActiveAgent(null, null);
  callbacks.onComplete();
}

/**
 * Run an edit pass on an existing document using Gemini.
 *
 * Flow:
 *   1. Chief of Staff uses Gemini to analyse which section to edit
 *   2. The specialist agent uses Gemini to rewrite that section
 *   3. Quality review verifies the change
 */
export async function runEdit(editRequest, currentDoc, callbacks) {
  // Phase 1: Chief of Staff analyses the edit
  callbacks.onActiveAgent('chief', `Analysing edit request: "${editRequest}"`);

  let sectionIdx = 0;
  let diffSummary = '';

  const sectionList = currentDoc.sections
    .map((s, i) => `[${i}] "${s.title}" (agent: ${s.agent}) — preview: ${(s.content || '').slice(0, 80)}...`)
    .join('\n');

  try {
    const routingResult = await withMinDelay(callGemini(
      `You are the Chief of Staff routing agent. Given a user's edit request and a list of document sections, determine which section should be modified. Respond in EXACTLY this format (two lines, nothing else):
SECTION_INDEX: <number>
SUMMARY: <one sentence describing what will change>`,
      `User's edit request: "${editRequest}"

Document sections:
${sectionList}

Which section index should be edited, and what is the change summary?`
    ), 1500);

    const idxMatch = routingResult.match(/SECTION_INDEX:\s*(\d+)/);
    const summaryMatch = routingResult.match(/SUMMARY:\s*(.+)/);

    if (idxMatch) sectionIdx = Math.min(parseInt(idxMatch[1], 10), currentDoc.sections.length - 1);
    if (summaryMatch) diffSummary = summaryMatch[1].trim();
  } catch (err) {
    console.error('Chief routing failed, using heuristic fallback:', err);
    callbacks.onError?.('Chief of Staff routing failed — using heuristic fallback');
    const fallback = matchEditToSectionFallback(editRequest, currentDoc);
    sectionIdx = fallback.sectionIdx;
    diffSummary = fallback.diffSummary;
  }

  if (!diffSummary) diffSummary = `Revised section based on: "${editRequest}"`;

  callbacks.onAgentComplete('chief');
  await delay(400);

  // Phase 2: Specialist agent rewrites the section
  const section = currentDoc.sections[sectionIdx];
  callbacks.onActiveAgent(section.agent, `Rewriting: ${section.title}`);
  await delay(400);
  callbacks.onSectionStart(sectionIdx);

  let newContent;
  try {
    newContent = await withMinDelay(callGemini(
      agentSystemPrompt(section.agent),
      `You are rewriting a section of a ${currentDoc.title}.

Section: "${section.title}"
Current content:
${section.content}

User's edit request: "${editRequest}"

Rewrite the section incorporating the user's requested change. Keep the same overall structure and [PLACEHOLDER] format. Output only the revised section text, no heading.`
    ), 1500);
  } catch (err) {
    console.error('Section rewrite failed:', err);
    callbacks.onError?.('Section rewrite failed — keeping original content');
    newContent = section.content;
  }

  callbacks.onSectionDone(sectionIdx, newContent);
  callbacks.onAgentComplete(section.agent);
  await delay(300);

  // Phase 3: Quality review of the change
  callbacks.onActiveAgent('quality', `Verifying edit in "${section.title}"`);

  try {
    await withMinDelay(callGemini(
      agentSystemPrompt('quality'),
      `Verify this edited section is consistent and well-formed:\n\nSection: "${section.title}"\nContent:\n${newContent}\n\nRespond briefly.`
    ), 1500);
  } catch (err) {
    console.error('Quality review of edit failed:', err);
    callbacks.onError?.('Edit quality review failed — skipping verification');
  }

  callbacks.onAgentComplete('quality');
  callbacks.onActiveAgent(null, null);

  callbacks.onChatMessage({
    role: 'assistant',
    content: `Done! I updated **${section.title}** via the ${getAgentName(section.agent)} agent.\n\n**What changed:** ${diffSummary}`,
  });

  callbacks.onEditComplete(sectionIdx, diffSummary);
}

/** Heuristic fallback if Gemini routing fails */
function matchEditToSectionFallback(editRequest, doc) {
  const lower = editRequest.toLowerCase();
  const sectionScores = doc.sections.map((s, idx) => {
    let score = 0;
    const combined = `${s.title} ${s.content || ''}`.toLowerCase();
    const words = lower.split(/\s+/).filter((w) => w.length > 3);
    for (const word of words) {
      if (combined.includes(word)) score += 1;
    }
    if (s.agent === 'termination' && (lower.includes('terminat') || lower.includes('notice') || lower.includes('cure'))) score += 3;
    if (s.agent === 'pricing' && (lower.includes('price') || lower.includes('fee') || lower.includes('cost') || lower.includes('payment'))) score += 3;
    if (s.agent === 'realestate' && (lower.includes('property') || lower.includes('title') || lower.includes('inspection'))) score += 3;
    if (s.agent === 'chief' && (lower.includes('party') || lower.includes('parties') || lower.includes('overview') || lower.includes('signature'))) score += 3;
    return { idx, score };
  });
  sectionScores.sort((a, b) => b.score - a.score);
  return { sectionIdx: sectionScores[0].idx, diffSummary: `Revised based on: "${editRequest}"` };
}

function getAgentName(agentId) {
  const names = { chief: 'Chief of Staff', termination: 'Termination Clause', realestate: 'Real Estate', pricing: 'Pricing', quality: 'Quality Review' };
  return names[agentId] || agentId;
}
