import { useEffect, useRef, useState } from 'react';
import { AGENT_MAP } from '../data/agents';

function TemplateText({ text }) {
  if (!text) return null;
  const parts = text.split(/(\[[A-Z_]+\])/g);
  return (
    <>
      {parts.map((part, i) => {
        const match = part.match(/^\[([A-Z_]+)\]$/);
        if (match) return <TemplateField key={i} name={match[1]} />;
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

function TemplateField({ name }) {
  const [value, setValue] = useState('');
  const [editing, setEditing] = useState(false);
  const inputRef = useRef(null);
  const label = name.replace(/_/g, ' ').toLowerCase();

  useEffect(() => {
    if (editing && inputRef.current) inputRef.current.focus();
  }, [editing]);

  if (editing || value) {
    return (
      <input
        ref={inputRef}
        type="text"
        value={value}
        placeholder={label}
        onChange={(e) => setValue(e.target.value)}
        onBlur={() => { if (!value) setEditing(false); }}
        className="inline bg-transparent border-b-2 border-indigo-300 text-indigo-700 font-medium px-0.5 min-w-[60px] text-sm focus:outline-none focus:border-indigo-500"
        style={{ width: `${Math.max(value.length || label.length, 8)}ch` }}
      />
    );
  }

  return (
    <button
      onClick={() => setEditing(true)}
      className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-amber-50 border border-amber-200 text-amber-700 text-xs font-medium hover:bg-amber-100 transition-colors cursor-pointer"
    >
      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
      </svg>
      {label}
    </button>
  );
}

export default function DocumentPane({ document, hasStarted, activeSectionIdx, qualityReviewActive }) {
  const sectionRefs = useRef({});
  const scrollContainerRef = useRef(null);

  useEffect(() => {
    if (activeSectionIdx >= 0 && sectionRefs.current[activeSectionIdx] && scrollContainerRef.current) {
      sectionRefs.current[activeSectionIdx].scrollIntoView({
        behavior: 'smooth',
        block: 'center',
      });
    }
  }, [activeSectionIdx]);

  if (!hasStarted) {
    return (
      <div className="flex flex-col items-center justify-center flex-1 bg-white px-12">
        <div className="w-16 h-16 rounded-2xl bg-slate-100 flex items-center justify-center mb-5">
          <svg className="w-8 h-8 text-slate-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
        </div>
        <h3 className="text-lg font-semibold text-slate-700 mb-2">No document yet</h3>
        <p className="text-sm text-slate-400 text-center max-w-xs leading-relaxed">
          Use the chat to describe the document you need. Our agents will collaborate to generate it in real time.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col flex-1 bg-white overflow-hidden">
      {/* Document header */}
      <div className="px-8 py-4 border-b border-slate-200">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center">
            <svg className="w-4 h-4 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <div>
            <h2 className="text-base font-semibold text-slate-800">{document.title}</h2>
            <p className="text-xs text-slate-400 mt-0.5">Generated by DocAgent</p>
          </div>
        </div>
      </div>

      {/* Document body */}
      <div ref={scrollContainerRef} className="flex-1 overflow-y-auto px-8 py-6 relative">
        {/* Quality review overlay — shimmer across the entire document */}
        {qualityReviewActive && (
          <div className="absolute inset-0 z-10 pointer-events-none section-loading rounded-none" data-agent="quality" />
        )}

        <div className="max-w-2xl mx-auto space-y-5">
          {document.sections.map((section, idx) => {
            const agent = AGENT_MAP[section.agent];
            const agentColor = agent?.color || '#6366f1';
            const agentName = agent?.name || section.agent;
            const colorClasses = getAgentColorClasses(section.agent);

            return (
              <div
                key={section.id}
                ref={(el) => { sectionRefs.current[idx] = el; }}
                className={`relative rounded-lg border p-5 transition-all duration-500 ${
                  section.status === 'loading'
                    ? `${colorClasses.border} section-loading`
                    : section.status === 'done'
                    ? 'border-slate-200'
                    : 'border-slate-100 bg-slate-50/50'
                }`}
                data-agent={section.agent}
              >
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-sm font-semibold text-slate-800">{section.title}</h3>
                  {section.status === 'loading' && (
                    <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-medium ${colorClasses.bg} ${colorClasses.text}`}>
                      <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: agentColor }} />
                      {agentName}
                    </span>
                  )}
                  {section.status === 'done' && (
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-emerald-50 text-emerald-600">
                      <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                      </svg>
                      Complete
                    </span>
                  )}
                  {section.status === 'pending' && (
                    <span className="text-[10px] text-slate-300">Queued</span>
                  )}
                </div>

                {section.status === 'loading' && (
                  <div className="flex items-center gap-2 py-3">
                    <div className="flex gap-1">
                      <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: agentColor, animationDelay: '0s' }} />
                      <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: agentColor, animationDelay: '0.3s' }} />
                      <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: agentColor, animationDelay: '0.6s' }} />
                    </div>
                    <p className={`text-xs italic ${colorClasses.text}`}>
                      {section.agentTask}
                    </p>
                  </div>
                )}

                {section.status === 'done' && section.content && (
                  <div className="text-sm text-slate-600 leading-relaxed whitespace-pre-line">
                    <TemplateText text={section.content} />
                  </div>
                )}

                {section.status === 'pending' && (
                  <div className="text-xs text-slate-300 italic">Waiting for agent...</div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

function getAgentColorClasses(agentId) {
  const map = {
    chief:       { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    termination: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    realestate:  { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200' },
    pricing:     { bg: 'bg-pink-50', text: 'text-pink-600', border: 'border-pink-200' },
    quality:     { bg: 'bg-violet-50', text: 'text-violet-600', border: 'border-violet-200' },
  };
  return map[agentId] || map.chief;
}
